#! /bin/sh

bspc monitor -d 1 2 3 4
bspc config top_padding					40
bspc config split_ratio					0.50
bspc config -d ^1 border_width		3
bspc config -d ^2 border_width		3
bspc config -d ^3 border_width		3
bspc config -d ^4 border_width		3

#bspc config border_radius 15
bspc config window_gap					30
bspc config borderless_monocle		true
bspc config gapless_monocle			true
bspc config focus_follows_pointer	true
bspc config normal_border_color 		"#1f242f"
bspc config active_border_color 		"#3f444f" 
bspc config focused_border_color 	"#3f444f"

bspc rule -a Chromium desktop=^2 follow=off state=floating
